- name: Build Jenkins Master
  hosts: localhost
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Build Jenkins Master role
      import_role:
        name: jenkins-master
