---
# tasks file for jenkins-master

# Setup/install tasks.
#- include_tasks: install.yml
#  tags: install
- name: Execute a command
  ansible.builtin.command: "false"
  debugger: on_failed


- name: Apply tags to tasks within included file
  include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - always

# Setup/uninstall tasks.
#- include_tasks: uninstall.yml
#  tags: uninstall

- name: Apply tags to tasks within included file
  include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - uninstall
  tags:
    - always

# https://medium.com/@saaduddin26/configure-jenkins-with-ansible-54717131776
# scripts to run to config jenkins from ansible
