---
# tasks file for jenkins-master

# Setup/install tasks.
- name: Execute a command
  ansible.builtin.command: "false"
  debugger: on_failed


- name: Include install tasks
  include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - always

- name: Include uninstall tasks
  include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - uninstall
  tags:
    - always

- name: Include node tasks
  include_tasks:
    file: node.yml
    apply:
      tags:
        - node
  tags:
    - always

# https://medium.com/@saaduddin26/configure-jenkins-with-ansible-54717131776
# scripts to run to config jenkins from ansible
